### ISSUE TITLE
Request: add a script to fix the run time permissions

### ISSUE THREAD

**Issue by williamgateszhao** [VR-25/MagicGApps#1]
MagicGApps 2017.7.29 from Magisk Manager, with MIUI 8.7.7.7 Beta, Android 7.1.1

I have to run 'pm grant' with root to fix those  permissions:
```
pm grant com.google.android.gms android.permission.ACCESS_FINE_LOCATION
```
otherwise GMS would cruhes from time to time.
```
pm grant com.google.android.syncadapters.calendar android.permission.READ_CALENDAR
pm grant com.google.android.syncadapters.calendar android.permission.WRITE_CALENDAR
```
otherwise google calendar would not been syned.
```
pm grant com.google.android.syncadapters.contacts android.permission.READ_CONTACTS
pm grant com.google.android.syncadapters.contacts android.permission.WRITE_CONTACTS
pm grant com.google.android.syncadapters.contacts android.permission.GET_ACCOUNTS
```
otherwise contacts would not been syned.

Could you please just add this script to this module?
https://github.com/opengapps/opengapps/wiki/Notes-for-Android-6.0

**Comment by VR-25** [comment]
I'm aware of the issue. What's behind me and solving it is my unreliable internet connection. Thanks for point that out though! Rest assured, the problem will be solved.

**Comment by VR-25** [comment]
I just managed to add /system/etc/default-permissions. See if that works for you. Also, consider [this](https://github.com/Magisk-Modules-Repo/MagicGApps) as the main repo for now. It's extremely hard to update both with such a bad internet connection.
